### ISSUE TITLE
iOS: Archiving fails, build succeeds

### ISSUE THREAD

**Issue by supmanyu** [cashfree/react-native-cashfree-pg-sdk#11]
Hi everyone,

![image-1](https://user-images.githubusercontent.com/13700827/201719069-5a56688e-1622-47fd-b24c-e08fb8ef109e.png)

react-native version: 0.64.3

getting this error when trying to archive a build for uploading to app store, removing the library allows the archive to succeed, I'm willing to give any additional that might be required, any help will be greatly appreciated.

**Comment by suhas-cashfree** [comment]
What is the xcode version you are using ?

**Comment by supmanyu** [comment]
13.4.1

**Comment by suhas-cashfree** [comment]
Please update to latest version of XCode (14+) and try

**Comment by supmanyu** [comment]
Thanks for the quick reply @suhas-cashfree, we have a library which fails to compile with newer versions of xcode, so we cant directly test it on the latest version. However, as soon as we are able to upgrade, i will test it out and report back, here, closing this issue for now.

**Comment by ketanuengage** [comment]
@suhas-cashfree The latest stable version of XCode is 13.4. No point of upgrading to beta versions. Please suggest valid workaround.

**Comment by ketanuengage** [comment]
@supmanyu  Was the issue resolved?

**Comment by supmanyu** [comment]
@ketanuengage unfortunately no, we had to go through with a payment link based approach by opening a webview with the payment link generated in the backend, and redirecting the user back to the app using a dynamically generated deeplink from firebase, since upgrading to xcode 14 was not an option for us as other libraries that we use do not currently support xcode 14.

**Comment by ketanuengage** [comment]
@supmanyu  thanks for updating on the issue. 
@suhas-cashfree Please reopen this issue as many are facing this problem and provide some valid solutions for it.
