### ISSUE TITLE
payment modal not opening after CFPaymentGatewayService.doPayment(dropPayment) in android

### ISSUE THREAD

**Issue by yprince19** [cashfree/react-native-cashfree-pg-sdk#12]
<img width="587" alt="image" src="https://user-images.githubusercontent.com/96334566/202099834-7f6fc246-cd03-4dba-9f50-428b1204e2a0.png">
Hi, Cashfree payment modal not opening after "CFPaymentGatewayService.doPayment(dropPayment)" executes. It's not throwing any error as well. Working fine on iOS but nothing happens on android.

**Comment by malikzype** [comment]
Facing same issue +1

**Comment by iammurali** [comment]
Facing same issue +1

**Comment by malikzype** [comment]
We managed to solve the issue. Our issue was regarding theme. We were passing an gradient array in text which is not accepted. Passing a normal string hex color, our code worked. Hope this helps

**Comment by softgenicsShubham** [comment]
i'm also facing the same issues

**Comment by kishan-cashfree** [comment]
Please try our latest SDK and let us know if you are still facing this issue.
