### ISSUE TITLE
Payment components are either not enabled or not applicable for this order

### ISSUE THREAD

**Issue by digitstringstech** [cashfree/react-native-cashfree-pg-sdk#14]
CFPaymentGatewayService.doPayment() throws error following exception:

`{"status":"ERROR","message":"Payment components are either not enabled or not applicable for this order","code":"payment_failed","type":"request_failed"}`
<img width="822" alt="Screenshot 2022-11-25 at 12 25 12" src="https://user-images.githubusercontent.com/97337992/203985623-22debdde-7c82-40ec-b9fa-c3fdbfcca511.png">

Same code used to work couple of days ago. Is there any change in the API? 
This is a blocker for us. Kindly advise, what needs to be done to avoid this error.

Thank you

**Comment by suhas-cashfree** [comment]
Hi @digitstringstech 
Please write to care@cashfree.com with the email ID that you use to login to Cashfree with this query.
