### ISSUE TITLE
Swift Compiler Error in iOS while archiving

### ISSUE THREAD

**Issue by ketanuengage** [cashfree/react-native-cashfree-pg-sdk#16]
Getting Swift Compiler Error in Xcode while archiving, although build works fine in debug.
Cannot find type 'CFPaymentGatewayService' in scope

Please find the below configurations that I am using
"react-native-cashfree-pg-sdk": "1.0.2",
"react-native": "0.63.3"

Please check the attached screenshot.

<img width="524" alt="Screenshot 2022-12-13 at 1 33 07 PM" src="https://user-images.githubusercontent.com/81960114/207260065-0fdcbd61-caf5-46e3-bb78-79d8c92ce88e.png">

**Comment by suhas-cashfree** [comment]
It's happening only why Archiving ?

**Comment by ketanuengage** [comment]
@suhas-cashfree  Yes

**Comment by ketanuengage** [comment]
Now while building also this error comes up.

**Comment by suhas-cashfree** [comment]
Hi @ketanuengage please write to care@cashfree.com with the email ID registered with Cashfree so that we can connect and check this issue further.
