### ISSUE TITLE
Not able to run the Repo

### ISSUE THREAD

**Issue by VinayakQubited** [cashfree/react-native-cashfree-pg-sdk#19]
Error: The package 'react-native-cashfree-pg-api' doesn't seem to be linked. Make sure: 

- You rebuilt the app after installing the package
- You are not using Expo managed workflow

This error is located at:
    in NavigationContainer (at App.tsx:225)
    in RCTView (at SafeAreaView.js:40)
    in SafeAreaView (at App.tsx:224)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:411)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in ForwardRef(NavigationContainer) (at App.tsx:223)
    in App (at renderApplication.js:40)
    in RCTView (at AppContainer.js:101)
<img width="327" alt="Screenshot 2022-12-19 at 1 51 59 PM" src="https://user-images.githubusercontent.com/120651206/208379960-97392060-6e39-42d2-bba0-65aa07189877.png">

    in RCTView (at AppContainer.js:119)

**Comment by tatva-kashmeera** [comment]
Any update on this issue ?

> Error: The package 'react-native-cashfree-pg-api' doesn't seem to be linked. Make sure:
> 
> * You rebuilt the app after installing the package
> * You are not using Expo managed workflow
> 
> This error is located at: in NavigationContainer (at App.tsx:225) in RCTView (at SafeAreaView.js:40) in SafeAreaView (at App.tsx:224) in EnsureSingleNavigator (at BaseNavigationContainer.tsx:411) in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:91) in ThemeProvider (at NavigationContainer.tsx:90) in ForwardRef(NavigationContainer) (at App.tsx:223) in App (at renderApplication.js:40) in RCTView (at AppContainer.js:101) <img alt="Screenshot 2022-12-19 at 1 51 59 PM" width="327" src="https://user-images.githubusercontent.com/120651206/208379960-97392060-6e39-42d2-bba0-65aa07189877.png">
> 
> ```
> in RCTView (at AppContainer.js:119)
> ```

Facing same issue.

**Comment by tatva-simran** [comment]
Facing same issue

**Comment by kishan-cashfree** [comment]
@VinayakQubited @tatva-simran 
Please let us know if you are still facing the same issue?

**Comment by kishan-cashfree** [comment]
Closing this issue as it is not reproducible.

**Comment by kundan175** [comment]
@kishan-cashfree still not working 

![Image](https://github.com/user-attachments/assets/afd38b07-db74-4354-bc03-42b628f0dfaa)
