### ISSUE TITLE
Android build error

### ISSUE THREAD

**Issue by sagar1garg** [cashfree/react-native-cashfree-pg-sdk#20]
`Could not find a declaration file for module 'react-native-cashfree-pg-sdk'. '/Users/sagar/Desktop/consulting_2.0/node_modules/react-native-cashfree-pg-sdk/lib/commonjs/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-native-cashfree-pg-sdk` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-cashfree-pg-sdk';`ts(7016)`

I am getting this error while trying to build for android. Kindly provide a solution.

**Comment by aabhasr1** [comment]
is this issue resolved?
