### ISSUE TITLE
Package name not enabled or approved

### ISSUE THREAD

**Issue by yasvitajoshi309** [cashfree/react-native-cashfree-pg-sdk#22]
Hello, we are using react-native-cashfree-pg-sdk 2.0.2 for payment. It works fine in staging, However,  in Production environment it's failed with error like com.abc (packagename) is not enabled or approved
can anyone please suggest me any solution for this ?

**Comment by suhas-cashfree** [comment]
Hi @yasvitajoshi309 reach out to care@cashfree.com or your account manager to get your package whitelisted.
