### ISSUE TITLE
Payment modal getting closes as soon as it opens on CFPaymentGatewayService.doPayment(dropPayment)

### ISSUE THREAD

**Issue by Ritz1998** [cashfree/react-native-cashfree-pg-sdk#25]
const session = new CFSession(
                        response.cftoken,
                        response.orderId,
                        CFEnvironment.SANDBOX
                    );
                    // console.log("CFPaymentComponentBuilder",CFPaymentComponentBuilder)
                    const paymentModes = new CFPaymentComponentBuilder()
                    .add(CFPaymentModes.CARD)
                    .add(CFPaymentModes.UPI)
                    .add(CFPaymentModes.NB)
                    .add(CFPaymentModes.WALLET)
                    .add(CFPaymentModes.PAY_LATER)
                    .build();
                    const theme = new CFThemeBuilder()
                        .setNavigationBarBackgroundColor('#E64A19')
                        .setNavigationBarTextColor('#FFFFFF')
                        .setButtonBackgroundColor('#FFC107')
                        .setButtonTextColor('#FFFFFF')
                        .setPrimaryTextColor('#212121')
                        .setSecondaryTextColor('#757575')
                        .build();

                    const dropPayment = new CFDropCheckoutPayment(session, paymentModes, theme);

                    CFPaymentGatewayService.doPayment(dropPayment)

**Comment by aabhasr1** [comment]
Can you log the failure callback and check what is the error message and code

**Comment by Ritz1998** [comment]
@aabhasr1  There is no error in log not even in catch block

**Comment by softgenicsShubham** [comment]
i'm also getting the same issues. how can i solve it?

**Comment by kherajanid** [comment]
CFPaymentGatewayService.setCallback({
      onVerify(orderID) {
        console.log('orderId is :' + orderID);
        setIsPaymentInitiated(false);
      },
      
      onError(error, orderID) {
        setIsPaymentInitiated(false);
        console.log('exception is : ' + JSON.stringify(error) + '\norderId is :' + orderID);
      },
    });

use setCallback to track error

**Comment by paliwalamol** [comment]
any solution for this?
