### ISSUE TITLE
Cannot find module 'react-native-cashfree-pg-sdk' or its corresponding type declarations.ts

### ISSUE THREAD

**Issue by crstnmac** [cashfree/react-native-cashfree-pg-sdk#28]
Type errors

**Comment by vidurajith-darshana** [comment]
I fixed that issue by removing .tsx and adding the .js to my file extension. for example,

`App.tsx` -> `App.js`

**Comment by kishan-cashfree** [comment]
@crstnmac is this resolved?

**Comment by kishan-cashfree** [comment]
Closing this bug as this is not reproducible on our end. Please let us know if you face it again.
