### ISSUE TITLE
payments working in emulator but failing in Real device

### ISSUE THREAD

**Issue by kherajanid** [cashfree/react-native-cashfree-pg-sdk#29]
reason: "{\"error\":\"{\\\"status\\\":\\\"FAILED\\\",\\\"message\\\":\\\"com.packagename is not trusted. App should be installed from app store.\\\",\\\"code\\\":\\\"android_package_not_approved\\\",\\\"type\\\":\\\"feature_not_enabled\\\"}\",\"orderID\":\"xxxxxxx\"}"

App package name is already approoved .

function **doWebPayment(JSON.stringify(session))** is working fine but when we are **doPayment(dropPayment)** , It is showing the above error

**Comment by kishan-cashfree** [comment]
@kherajanid let us know if you are still facing this issue?

**Comment by kishan-cashfree** [comment]
@kherajanid  Closing this, since it is related to backend ops. Please reach out to [care@cashfree.com](mailto:care@cashfree.com) or your account manager to get your package whitelisted.
