### ISSUE TITLE
Android release build failed 

### ISSUE THREAD

**Issue by Nsingh0007** [cashfree/react-native-cashfree-pg-sdk#30]
* What went wrong:
Execution failed for task ':react-native-cashfree-pg-sdk:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/Desktop/All/Projects/node_modules/react-native-cashfree-pg-sdk/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:3: AAPT: error: resource android:color/system_neutral1_1000 not found.
         
     ERROR:/Users/Desktop/All/Projects/node_modules/react-native-cashfree-pg-sdk/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:4: AAPT: error: resource android:color/system_neutral1_900 not found.
         
     ERROR:/Users/Desktop/All/Projects/node_modules/react-native-cashfree-pg-sdk/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:5: AAPT: error: resource android:color/system_neutral1_0 not found.
         
     ERROR:/Users/Desktop/All/Projects/node_modules/react-native-cashfree-pg-sdk/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:6: AAPT: error: resource android:color/system_neutral1_800 not found.
         
     ERROR:/Users/Desktop/All/Projects/node_modules/react-native-cashfree-pg-sdk/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:7: AAPT: error: resource android:color/system_neutral1_700 not found.
         
     ERROR:/Users/Desktop/All/Projects/node_modules/react-native-cashfree-pg-sdk/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:8: AAPT: error: resource android:color/system_neutral1_600 not found.
         
     ERROR:/Users/Desktop/All/Projects/node_modules/react-native-cashfree-pg-sdk/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:9: AAPT: error: resource android:color/system_neutral1_500 not found.
         
     ERROR:/Users/Desktop/All/Projects/node_modules/react-native-cashfree-pg-sdk/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:10: AAPT: error: resource android:color/system_neutral1_400 not found.
         
     ERROR:/Users/Desktop/All/Projects/node_modules/react-native-cashfree-pg-sdk/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:11: AAPT: error: resource android:color/system_neutral1_300 not found.
         
     ERROR:/Users/Desktop/All/Projects/node_modules/react-native-cashfree-pg-sdk/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:12: AAPT: error: resource android:color/system_neutral1_200 not found.
         
     ERROR:/Users/Desktop/All/Projects/node_modules/react-native-cashfree-pg-sdk/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:13: AAPT: error: resource android:color/system_neutral1_100 not found.
         
     ERROR:/Users/Desktop/All/Projects/node_modules/react-native-cashfree-pg-sdk/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:14: AAPT: error: resource android:color/system_neutral1_50 not found.
         
     ERROR:/Users/Desktop/All/Projects/node_modules/react-native-cashfree-pg-sdk/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:15: AAPT: error: resource android:color/system_neutral1_10 not found.
         
     ERROR:/Users/Desktop/All/Projects/node_modules/react-native-cashfree-pg-sdk/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:16: AAPT: error: resource android:color/system_neutral2_1000 not found.
         
     ERROR:/Users/Desktop/All/Projects/node_modules/react-native-cashfree-pg-sdk/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:17: AAPT: error: resource android:color/system_neutral2_900 not found.
         
     ERROR:/Users/Desktop/All/Projects/node_modules/react-native-cashfree-pg-sdk/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:18: AAPT: error: resource android:color/system_neutral2_0 not found.
         
     ERROR:/Users/Desktop/All/Projects/node_modules/react-native-cashfree-pg-sdk/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:19: AAPT: error: resource android:color/system_neutral2_800 not found.
         
     ERROR:/Users/Desktop/All/Projects/node_modules/react-native-cashfree-pg-sdk/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:20: AAPT: error: resource android:color/system_neutral2_700 not found.
         
     ERROR:/Users/Desktop/All/Projects/node_modules/react-native-cashfree-pg-sdk/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:21: AAPT: error: resource android:color/system_neutral2_600 not found.
         
     ERROR:/Users/Desktop/All/Projects/node_modules/react-native-cashfree-pg-sdk/android/build/intermediates/merged_res/release/values-v31/values-v31.xml:22: AAPT: error: resource android:color/system_neutral2_500 not found.

Here is the all dependencies of package.json file 

"dependencies": {
    "@react-native-async-storage/async-storage": "^1.17.10",
    "@react-native-clipboard/clipboard": "^1.11.1",
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.0",
    "axios": "^0.27.2",
    "cashfree-pg-api-contract": "^2.0.1",
    "class-transformer": "^0.5.1",
    "formik": "^2.2.9",
    "i18next": "^21.10.0",
    "jwt-decode": "^3.1.2",
    "lodash": "^4.17.21",
    "lottie-react-native": "^5.1.5",
    "mobx": "^6.6.2",
    "mobx-react": "^7.5.3",
    "moment": "^2.29.4",
    "react": "18.1.0",
    "react-i18next": "^11.18.6",
    "react-native": "^0.70.1",
    "react-native-base64": "^0.2.1",
    "react-native-blob-util": "^0.17.3",
    "react-native-cashfree-pg-sdk": "^2.0.7",
    "react-native-circular-progress-indicator": "^4.4.2",
    "react-native-curved-bottom-bar": "^3.2.2",
    "react-native-fast-image": "^8.6.1",
    "react-native-flash-message": "^0.4.0",
    "react-native-floating-label-input": "^1.4.2",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-gifted-charts": "^1.2.42",
    "react-native-image-crop-picker": "^0.38.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-modalize": "^2.1.1",
    "react-native-orientation-locker": "^1.5.0",
    "react-native-otp-inputs": "^7.4.0",
    "react-native-outside-press": "^1.1.0",
    "react-native-pdf": "^6.6.2",
    "react-native-permissions": "^3.6.1",
    "react-native-portalize": "^1.0.7",
    "react-native-reanimated": "^2.15.0",
    "react-native-reanimated-carousel": "^3.0.6",
    "react-native-render-html": "^6.3.4",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "^3.17.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-svg": "^13.9.0",
    "react-native-toast-message": "^2.1.5",
    "react-native-vector-icons": "^9.2.0",
    "react-native-video": "^5.2.1",
    "react-native-video-controls": "^2.8.1",
    "react-native-video-player": "^0.14.0",
    "react-native-webview": "^12.0.1",
    "yarn": "^1.22.19",
    "yup": "^1.0.2"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.72.1",
    "react-native-svg-transformer": "^1.0.0",
    "react-test-renderer": "18.1.0"
  },

**Comment by Nsingh0007** [comment]
please help me out.
if anyone has the solution for it.

**Comment by znyrpavithra** [comment]
I have the same problem. Please give us a solution to this problem

**Comment by Nsingh0007** [comment]
using VS code terminal Build is failed, but while creating build using android studio the build created successfully.

unable to understand why it's happening like that.

**Comment by yhdesai** [comment]
I'm getting this same error

**Comment by Nsingh0007** [comment]
I found the solution.

Instead of creating APK or bundle from VSCode terminal command.
Please create build from Android Studio. APK will work fine.

**Comment by rishCodere** [comment]
This error is due to the following line of code in node_modules/react-native-cashfree-pg-sdk/android/build.gradle: 

`android {
    compileSdkVersion safeExtGet('CashfreePgApi_compileSdkVersion', 29)
    defaultConfig {
        minSdkVersion safeExtGet('CashfreePgApi_minSdkVersion', 19)
        targetSdkVersion safeExtGet('CashfreePgApi_targetSdkVersion', 29)
....
`

Remove "CashfreePgApi_" from all three safeExtGet() function, it is not able to read your app defualt compilesdkversion, minsdkversion and targetsdkversion.
