### ISSUE TITLE
IOS app crash while doing payment

### ISSUE THREAD

**Issue by lakshyastech** [cashfree/react-native-cashfree-pg-sdk#31]
try {
            const session = new CFSession(
              res?.data?.payment_session_id,
              res?.data?.order_id,
              CFEnvironment.PRODUCTION
            );
            CFPaymentGatewayService.doWebPayment(JSON.stringify(session));
**after this above method .doWebPayment my app crashed without any logs***
            CFPaymentGatewayService.setCallback({
              onVerify(res) {
                addDataIntoFirebase(res, amount);
              },
              onError(error) {
                toastWithIcon(`Transaction Failed!`);
                setLoading2(false);
              },
            });

**Comment by suhas-cashfree** [comment]
Try setting the callback before invoking doWebPayment

**Comment by kishan-cashfree** [comment]
@lakshyastech Closing this issue since it is working as expected.
