### ISSUE TITLE
Android Build Issue RN 0.72

### ISSUE THREAD

**Issue by rnkdsh** [cashfree/react-native-cashfree-pg-sdk#32]
After I upgraded the React Native version to 0.72 I am getting this error while building Android project.

<img width="847" alt="Screenshot 2023-06-23 at 12 43 14 PM" src="https://github.com/cashfree/react-native-cashfree-pg-sdk/assets/16722278/dcbd84ea-83e0-4ad9-81cf-28e39c8f7191">

**Comment by kishan-cashfree** [comment]
@rnkdsh It will be fixed in the new coming release 2.0.9

**Comment by kishan-cashfree** [comment]
https://www.npmjs.com/package/react-native-cashfree-pg-sdk?activeTab=readme
We have released a new SDK 2.0.9. Please try now.
