### ISSUE TITLE
SQL Injection security issue (EXTERNAL DATA IN SQL QUERIES) CFDatabaseHelper

### ISSUE THREAD

**Issue by PraveenKumar8912** [cashfree/react-native-cashfree-pg-sdk#48]
Team,
We are facing a SQL Injection security issue (EXTERNAL DATA IN SQL QUERIES) in the following code which is present in CFDatabaseHelper.class , is there any way to update this code to overcome this.

    public void onCreate(SQLiteDatabase db) {
        db.execSQL("create table PAYMENT_EVENT(_id TEXT PRIMARY KEY, environment TEXT NOT NULL, app_id TEXT NOT NULL, sdk_version TEXT NOT NULL, release_version TEXT NOT NULL, source TEXT NOT NULL, request_id TEXT NOT NULL, contexts TEXT NOT NULL, timestamp INTEGER NOT NULL);");
        db.execSQL("create table USER_EVENT(_id TEXT NOT NULL, name TEXT NOT NULL, network_type TEXT NOT NULL, free_ram TEXT NOT NULL, extra_params TEXT , timestamp INTEGER NOT NULL);");
        db.execSQL("create table USER_EXCEPTION(_id TEXT NOT NULL, exception_level TEXT NOT NULL, exception_culprit TEXT NOT NULL, exception_values TEXT NOT NULL, timestamp INTEGER NOT NULL);");
    }

    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        db.execSQL(this.dropTableQuery("PAYMENT_EVENT"));
        db.execSQL(this.dropTableQuery("USER_EVENT"));
        db.execSQL(this.dropTableQuery("USER_EXCEPTION"));
        db.execSQL("create table PAYMENT_EVENT(_id TEXT PRIMARY KEY, environment TEXT NOT NULL, app_id TEXT NOT NULL, sdk_version TEXT NOT NULL, release_version TEXT NOT NULL, source TEXT NOT NULL, request_id TEXT NOT NULL, contexts TEXT NOT NULL, timestamp INTEGER NOT NULL);");
        db.execSQL("create table USER_EVENT(_id TEXT NOT NULL, name TEXT NOT NULL, network_type TEXT NOT NULL, free_ram TEXT NOT NULL, extra_params TEXT , timestamp INTEGER NOT NULL);");
        db.execSQL("create table USER_EXCEPTION(_id TEXT NOT NULL, exception_level TEXT NOT NULL, exception_culprit TEXT NOT NULL, exception_values TEXT NOT NULL, timestamp INTEGER NOT NULL);");
    }

**Comment by kishan-cashfree** [comment]
@PraveenKumar8912 Can you help with your Cashfree SDK version?

**Comment by PraveenKumar8912** [comment]
@kishan-cashfree this issue we received when using v 1.0.2 after that I have updated the library to the latest version 2.1.7, in this also we observer the same. 

We are using cashfree-pg-api-contract v1.0.0 as well.

**Comment by kishan-cashfree** [comment]
@PraveenKumar8912  `react-native-cashfree-pg-sdk` latest Version is 2.1.7  ( https://www.npmjs.com/package/react-native-cashfree-pg-sdk) 
` cashfree-pg-api-contrac`t  2.0.5 ( https://www.npmjs.com/package/cashfree-pg-api-contract) 

Can you clear the cache and reinstall fresh deps from cash-free SDK? 
Also, Delete your npm module folder.  

SQL Injection security is already fixed in July.

**Comment by PraveenKumar8912** [comment]
Thanks @kishan-cashfree I will check and update you.

**Comment by kishan-cashfree** [comment]
Closing since this is resolved already.
