### ISSUE TITLE
something went wrong, Request_failed

### ISSUE THREAD

**Issue by ajf1016** [cashfree/react-native-cashfree-pg-sdk#52]
<img width="420" alt="Screenshot 2024-01-19 at 5 52 49 PM" src="https://github.com/cashfree/react-native-cashfree-pg-sdk/assets/83690916/a19fb59b-dcaa-49f4-a2f5-8917402d0121">

after some time loading, i get this repsonse : 

 LOG  errorString :{"status":"FAILED","message":"something went wrong","code":"payment_failed","type":"request_failed"}
 LOG  errorStringObject :[object Object]
 LOG  exception is : {"status":"FAILED","message":"something went wrong","code":"payment_failed","type":"request_failed"}
orderId is :ONERP-ORD-0000000064
 LOG  UPDATE STATUS :  {"status":"FAILED","message":"something went wrong","code":"payment_failed","type":"request_failed"}

**Comment by kishan-cashfree** [comment]
@ajf1016 
Can you please help Environment (SANDBOX /PROD)  and SDK version that you are using?

**Comment by ajf1016** [comment]
> @ajf1016 Can you please help Environment (SANDBOX /PROD) and SDK version that you are using?

 Environment : SANDBOX
 SDK Version : 2.1.7

**Comment by kishan-cashfree** [comment]
Can you also share the paymentSessionId ?

**Comment by ajf1016** [comment]
> Can you also share the paymentSessionId ?

session_nM8t1j1lYDUlZnuDAopj9zkbPFAIaj87rEedH0J1iGuvnhaHULbvwJQ_HVb794nyKnDd7YvQ55hXqJYvfQOyvmxaC-kaZMJEG_2RD8OtrUZz

**Comment by kishan-cashfree** [comment]
@ajf1016 This paymentSessionId belongs to PROD.

Can you please check you are creating an order in SANDBOX env and using SANDBOX env to open SDK?

**Comment by ajf1016** [comment]
> @ajf1016 This paymentSessionId belongs to PROD.
> 
> Can you please check you are creating an order in SANDBOX env and using SANDBOX env to open SDK?
