### ISSUE TITLE
payment_session_id is not present or is invalid

### ISSUE THREAD

**Issue by rajtessrac** [cashfree/react-native-cashfree-pg-sdk#55]
I am able to create order successfully. and getting intialing payment checkout  but getting error after entering card detail and pressing pay button

 **### exception is : {"status":"FAILED","message":"payment_session_id is not present or is invalid","code":"payment_session_id_invalid","type":"request_failed"}**

 ```
 const headers = {
      'Content-Type': 'application/json',
      'x-client-id': CASH_FREE.API_KEY,
      'x-client-secret': CASH_FREE.SECREAT_KEY,
      'x-api-version': '2021-05-21',
    };
    configureBaseURL(URLS.CASHFREE_BASE_URL);
    try {
      const order = await cashFreeServices.createCashFreeOrder(params, headers);
      console.log('order', order);
      const session = new CFSession(order.order_token, order.order_id, CFEnvironment.SANDBOX);
      const paymentModes = new CFPaymentComponentBuilder()
        .add(CFPaymentModes.CARD)
        .add(CFPaymentModes.UPI)
        .add(CFPaymentModes.NB)
        .add(CFPaymentModes.WALLET)
        .add(CFPaymentModes.PAY_LATER)
        .build();
      const theme = new CFThemeBuilder()
        .setNavigationBarBackgroundColor('#E64A19')
        .setNavigationBarTextColor('#FFFFFF')
        .setButtonBackgroundColor('#FFC107')
        .setButtonTextColor('#FFFFFF')
        .setPrimaryTextColor('#212121')
        .setSecondaryTextColor('#757575')
        .build();
      const dropPayment = new CFDropCheckoutPayment(session, paymentModes, theme);
      console.log(JSON.stringify(dropPayment));
      CFPaymentGatewayService.doPayment(dropPayment);
```

**Comment by suhas-cashfree** [comment]
When you create order change x-api-version to 2023-08-01 and in the response you will get payment_session_id. Pass that instead of order_token

**Comment by rajtessrac** [comment]
Working but after successful transaction I am getting only orderId is :order_1100582eX0SCpDAJThIWcxyIsdjrnhGMX

How do I get this type of json object {"orderAmount":"100.00","orderId":"1711968413","paymentMode":"DEBIT_CARD","referenceId":"14933917357","signature":"XGQeHHg877NV9Dm4fFwfAHqBYskTTEhGJ5fFMRfMWUc=","txMsg":"Transaction Successful","txStatus":"SUCCESS","txTime":"2024-04-01 16:17:06"}

**Comment by suhas-cashfree** [comment]
We do not send the transaction status anymore from the SDK.

Now using the order_id, you have to make an API call. Check this API -> https://docs.cashfree.com/reference/pgorderfetchpayments

**Comment by rajtessrac** [comment]
it's working but I am not getting any signatures like "signature": "XGQeHHg877NV9Dm4fFwfAHqBYskTTEhGJ5fFMRfMWUc=", how to I get this?

**Comment by rajtessrac** [comment]
I know I need signature for reference only and we will store into our local DB. so after transaction how do we get it?

**Comment by suhas-cashfree** [comment]
You will not get it. Use the order to verify the payment status from your backend directly. No need to use signature anymore.
Make a server to server call from your backend to Cashfree and fetch the payments for order
