### ISSUE TITLE
Virus Total Flagging app with "react-native-cashfree-pg-sdk" as malware

### ISSUE THREAD

**Issue by Shubham-UMR** [cashfree/react-native-cashfree-pg-sdk#57]
My ads account was blocked due to malware detected in app, when checked deeper by removing dependencies one by one, we have found that "react-native-cashfree-pg-sdk" is causing the issue, we have also tested a boilerplate app with just one package installed, at was immediately, started flagging it, please check

Virus Total Link : https://www.virustotal.com/gui/file/063d400522a5992430f82dbace1e9e3f2d9693c7db4ffdd0c0b02231f6632c11

<img width="1279" alt="image" src="https://github.com/cashfree/react-native-cashfree-pg-sdk/assets/105772245/340cfe59-5c30-41e4-98d6-003583643660">

**Comment by Shubham-UMR** [comment]
@kishan-cashfree @arjun-cashfree can you please check once.

**Comment by kishan-cashfree** [comment]
@Shubham-UMR 
Can you share more details like what is exactly causing?

When we checked for ESET-NOD32, it appeared to be a false positive.
https://forum.eset.com/topic/40076-my-partner-got-eset-nod32-a-variant-of-androidagenteur-on-virustotal-integrating-my-lib-for-android/

**Comment by Shubham-UMR** [comment]
Hello @kishan-cashfree, we also could not find the exact issue, but as per meta, they flagged the app for malware, and the only package Virus Total is flagging is cashfree, post package remove, it passes are checks, and as we use cashfree for payment gateway, we are not able to remove package.
The false positive you have mentioned is for "Android/Agent.EUR" but we are seeing "Android/FraudApp.AR" with cashfree package.

**Comment by Shubham-UMR** [comment]
@kishan-cashfree just checked again after the comment, seems it is not flagging now, so I think it was a false positive. @kishan-cashfree thanks for your time and efforts.

<img width="1279" alt="image" src="https://github.com/cashfree/react-native-cashfree-pg-sdk/assets/105772245/e4d1e111-436c-47b6-a109-ae901b566241">

**Comment by kishan-cashfree** [comment]
Closing as it was a `false positive` from virustotal
