### ISSUE TITLE
Some configuration issues

### ISSUE THREAD

**Issue by SamarthKadam** [cashfree/react-native-cashfree-pg-sdk#65]
I have used web checkout. So I've got some problems here they are.
![1e3aadc5-c64e-472a-8ac6-cde573cf0b64](https://github.com/user-attachments/assets/ddea8f1f-afdc-463c-8881-77662e9e9a47)
1> How Do I add icon in there and also add merchant name
2>Whenever i click Quick UPI like Gpay or Phonepay it loads and doesn't do anything. (is it due to because of test mode?)

Please help me with this

**Comment by kishan-cashfree** [comment]
@SamarthKadam 
1. You can change/modify the configuration from the merchant dashboard.  `https://merchant.cashfree.com/auth/login`

2. In SANDBOX env, It will open the Cashfree simulator page. and in PROD env, it will open the actual PSP app for payment.

Please share the relevant video and `paymentSessionId` so that we can debug it from our end.

You can join our discord channel for quicker resolution.
https://discord.gg/g6WhD7H9

**Comment by SamarthKadam** [comment]
Here is the app in test mode. Other payments options works fine with proper
simulation done. But when I click quick upi it loads here is the video sent
to you for the reference

**Comment by kishan-cashfree** [comment]
@SamarthKadam Can you please upload the video? Its not there in your comment

**Comment by kishan-cashfree** [comment]
Maybe you can try our UPI simulator APP for SANDBOX env..
https://docs.cashfree.com/docs/cashfree-upi-intent-simulator-apk

**Comment by SamarthKadam** [comment]
When I set to production. My previous configuration would work fine right?

**Comment by kishan-cashfree** [comment]
which previous configuration?

This is just a sample testing app. 
https://github.com/cashfree/react-native-cashfree-pg-sdk/issues/65#issuecomment-2295263554

**Comment by SamarthKadam** [comment]
I mean now upi is not working right as its in test mode. Im asking will it
work fine when working in production mode?

**Comment by kishan-cashfree** [comment]
In SANDBOX, it will open a cashfree simulator URL page. and in PROD, it will open the PSP app.

In test mode, it should open the HTTP URL page, if it is not opening then please paymentSessionId
will check this issue.

**Comment by kishan-cashfree** [comment]
@SamarthKadam  Please let us know if you are still facing the issue.

**Comment by SamarthKadam** [comment]
No Im not. Thank you

**Comment by kishan-cashfree** [comment]
@SamarthKadam Thanks for the update. Closing this now. Feel free to reopen if you again face the issue.

You can join our discord channel for quicker resolution.
https://discord.gg/g6WhD7H9
